order:
 - welkom
 - instructies



slides:

  welkom:
    title: Welkom
    background: welkom
    text: |
      Welkom op de dijkmate website
      asdasd
      asdasd
      asdasd


  instructies:
    title: Instructies
    text: |
      Dit is hoe het werkt

