order:
 - welkom
 - instructies



slides:

  welkom:
    title: Falco
    background: falco.jpg
    text: |
      # palla
      - hoi
      - a


  instructies:
    title: Instructies
    text: |
      ## Dit is hoe het werkt
      ---

      - palla
      - palla
      - kerelman
      - oke

      ---

      oke

    html: |
      <strong> gast </strong>
