order:
 - welkom
 - instructies



slides:

  welkom:
    title: Welkom
    background: test.png
    text: |
      Plaaatjeee


  instructies:
    title: Instructies
    text: |
      ## Dit is hoe het werkt
      - palla
      - oke
      - hoi

      ---

      oke

